### ISSUE TITLE
People index error

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1417]
### Descriptive summary

People index results in error.

```
NoMethodError in Hyrax::UsersController#index
undefined method `all' for Hyrax::User:Module

         query = ''
         appending = false
>>      base = User.all
         base.each do |user|
         next unless user.admin? || user_work_count(user) < 1
         query += " and " if appending

app/controllers/hyrax/users_controller.rb:47:in `exclude_admin_users_and_non_owners'
app/controllers/hyrax/users_controller.rb:31:in `base_query'
app/controllers/hyrax/users_controller.rb:13:in `search'
```

### Steps to reproduce the behavior

1. Click `View People`

**Comment by lawhorkl** [comment]
I click onto the nav bar and the index for People comes up fine for me...

Closing for now.

![image](https://cloud.githubusercontent.com/assets/12615997/26797805/29e3b5f4-49fc-11e7-9f5d-77e6e0ee9ee3.png)
