### ISSUE TITLE
Editing a proxy deposited work causes an error

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1566]
Clicking save on the edit work page causes an error related to the change_manger helper. This is a problem with our application, not Hyrax.

**Comment by crowesn** [comment]
@13miciunasl I can't reproduce this error on local. More details?

**Comment by crowesn** [comment]
```
Redirected to http://localhost:3000/concern/permissions/vh53wv72q/confirm_access?locale=en
Completed 500 Internal Server Error in 1039ms (ActiveRecord: 21.7ms)


  
NoMethodError (undefined method `key?' for nil:NilClass):
  
app/helpers/change_manager/change_manager_helper.rb:46:in `edit_access?'
app/helpers/change_manager/change_manager_helper.rb:33:in `new_editor?'
app/helpers/change_manager/change_manager_helper.rb:9:in `block in queue_notifications_for_editors'
app/helpers/change_manager/change_manager_helper.rb:7:in `queue_notifications_for_editors'
app/controllers/concerns/scholar/works_controller_behavior.rb:29:in `update'
  Rendering /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (4.3ms)
  Rendering /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
  Rendering /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.5ms)
  Rendered /home/vagrant/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (21.2ms)
```

**Comment by crowesn** [comment]
Looks like @lawhorkl worked on this https://github.com/uclibs/scholar_uc/commit/4d7238f33d8896034f6ff01f0e23409997d7dfc2

**Comment by crowesn** [comment]
@lawhorkl this is the PR: https://github.com/uclibs/scholar_uc/pull/1264

**Comment by lawhorkl** [comment]
@crowesn it looks like whatever object was passed as `editor` to the function `new_editor` is nil. 'editor, initialized on line 8 of the `change_manager_helper`. Whatever change its trying to process, the object is missing the relevant editor data needed to send the email.

As this happens on proxy edit, I imagine the work does not return the proper edit users like when editing ones own work.

These methods are hooked into `the depositors_controller` on lines 10 and 16. Inspect those objects and that should help determine why the editor value is missing. I can take a look when I get in today.

**Comment by crowesn** [comment]
http://eileencodes.com/posts/actioncontroller-parameters-now-returns-an-object-instead-of-a-hash/
