### ISSUE TITLE
Ldp::Gone error after deleting a file from a work

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1577]
### Descriptive summary

LDP::Gone error when deleting fileset from work. Bug is present in upstream hyrax.

### Expected behavior

Should redirect to parent work show page.

### Actual behavior

```
Completed 500 Internal Server Error in 984ms (ActiveRecord: 14.0ms)                                                                                               [184/1185]
  
Ldp::Gone ():
  
ldp (0.6.4) lib/ldp/client/methods.rb:119:in `block in check_for_errors'
ldp (0.6.4) lib/ldp/client/methods.rb:117:in `tap'
ldp (0.6.4) lib/ldp/client/methods.rb:117:in `check_for_errors'
ldp (0.6.4) lib/ldp/client/methods.rb:25:in `block in head'
activesupport (5.0.3) lib/active_support/notifications.rb:166:in `instrument'
ldp (0.6.4) lib/ldp/client/methods.rb:17:in `head'
/home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
active-fedora (11.2.0) lib/active_fedora/initializing_connection.rb:22:in `head'
ldp (0.6.4) lib/ldp/resource.rb:59:in `head'
ldp (0.6.4) lib/ldp/resource.rb:42:in `new?'
active-fedora (11.2.0) lib/active_fedora/file.rb:64:in `new_record?'
active-fedora (11.2.0) lib/active_fedora/with_metadata/metadata_node.rb:39:in `ldp_source'
active-fedora (11.2.0) lib/active_fedora/with_metadata/metadata_node.rb:16:in `initialize'
active-fedora (11.2.0) lib/active_fedora/with_metadata.rb:18:in `new'
active-fedora (11.2.0) lib/active_fedora/with_metadata.rb:18:in `metadata_node'
active-fedora (11.2.0) lib/active_fedora/associations/directly_contains_one_association.rb:101:in `metadata_node_for_record'
active-fedora (11.2.0) lib/active_fedora/associations/directly_contains_one_association.rb:94:in `get_type_from_record'
active-fedora (11.2.0) lib/active_fedora/associations/directly_contains_one_association.rb:19:in `block in find_target'
active-fedora (11.2.0) lib/active_fedora/associations/directly_contains_one_association.rb:17:in `each'
active-fedora (11.2.0) lib/active_fedora/associations/directly_contains_one_association.rb:17:in `find_target'
active-fedora (11.2.0) lib/active_fedora/associations/association.rb:115:in `load_target'
active-fedora (11.2.0) lib/active_fedora/associations/association.rb:36:in `reload'
active-fedora (11.2.0) lib/active_fedora/associations/singular_association.rb:10:in `reader'
active-fedora (11.2.0) lib/active_fedora/associations/builder/association.rb:95:in `original_file'
hyrax (1.0.1) app/models/concerns/hyrax/file_set/characterization.rb:30:in `characterization_proxy'
hyrax (1.0.1) app/models/concerns/hyrax/file_set/characterization.rb:38:in `mime_type'
hyrax (1.0.1) app/services/hyrax/file_set_derivatives_service.rb:5:in `mime_type'
hyrax (1.0.1) app/services/hyrax/file_set_derivatives_service.rb:19:in `valid?'
hyrax (1.0.1) app/services/hyrax/derivative_service.rb:5:in `each'
hyrax (1.0.1) app/services/hyrax/derivative_service.rb:5:in `find'
hyrax (1.0.1) app/services/hyrax/derivative_service.rb:5:in `for'
hyrax (1.0.1) app/models/concerns/hyrax/file_set/derivatives.rb:57:in `file_set_derivatives_service'
hyrax (1.0.1) app/models/concerns/hyrax/file_set/derivatives.rb:51:in `cleanup_derivatives'
```

### Steps to reproduce the behavior

1. Create work with attached file
1. Edit work and delete file

### Related work

Hyrax: https://github.com/samvera/hyrax/issues/1070

**Comment by crowesn** [comment]
Might be fixed [here](https://github.com/samvera/hyrax/pull/1073)

**Comment by jayanthdeejay** [comment]
After the upgrade, I could not reproduce this error. Upgrade, as we expected, might have fixed this.

**Comment by crowesn** [comment]
https://github.com/samvera/active_fedora/issues/947

**Comment by jayanthdeejay** [comment]
My bad. Upgrade did resolve this issue.
