### ISSUE TITLE
Make configuration changes to accommodate Solr 7x

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1650]
### Descriptive summary

Solr 7.0.0 introduces an error. We merged a quick fix by [pinning solr_wrapper to 6.6.0] but it would be best to follow up and make the required config changes to accommodate solr 7.x

### Stack trace
```
solr-7.0.0.zip: |=======================================| 100% (Time: 00:00:04 )
solr-7.0.0.zip.md5: |===================================| 100% (Time: 00:00:00 )
rake aborted!
Failed to execute solr create: Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Copying configuration to new core instance directory:
/home/travis/build/uclibs/scholar_uc/tmp/solr-test/server/solr/hydra-test
Creating new core 'hydra-test' using command:
http://localhost:8985/solr/admin/cores?action=CREATE&name=hydra-test&instanceDir=hydra-test
ERROR: Error CREATEing SolrCore 'hydra-test': Unable to create core [hydra-test] Caused by: Setting default operator in schema (solrQueryParser/@defaultOperator) not supported
. Further information may be available in tmp/solr-test/logs
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:322:in `exec'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:159:in `create'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:216:in `with_collection'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/active-fedora-11.4.0/lib/active_fedora/rake_support.rb:26:in `block in with_server'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:65:in `wrap'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper.rb:43:in `wrap'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/active-fedora-11.4.0/lib/active_fedora/rake_support.rb:17:in `with_server'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/active-fedora-11.4.0/lib/active_fedora/rake_support.rb:4:in `with_test_server'
/home/travis/build/uclibs/scholar_uc/lib/tasks/ci.rake:11:in `block in <top (required)>'
/home/travis/build/uclibs/scholar_uc/lib/tasks/ci.rake:19:in `block in <top (required)>'
/home/travis/build/uclibs/scholar_uc/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spec_with_app_load
(See full trace by running task with --trace)
```

### Related work

https://github.com/uclibs/scholar_uc/pull/1649

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/pull/1711/files

**Comment by crowesn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint - Scholar 3.0 🐞🐞🐞](https://trello.com/c/7H19ZUWH/25-sprint-scholar-30-%F0%9F%90%9E%F0%9F%90%9E%F0%9F%90%9E)

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
