### ISSUE TITLE
Error when editing and saving work 8623hx82z

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1723]
When editing and saving this work:
https://scholar-prod.uc.edu/concern/images/8623hx82z
the user sees an error screen.
However, the changes to the work to persist.

The log indicates that something related to the work's DOI is causing the error:
```
F, [2017-11-07T11:08:27.200059 #1171] FATAL -- : [3a4f5e93-f355-4db9-829c-08cd9980a53e] NoMethodError (undefined method `permanent_url_for' for Scholar:Module):
F, [2017-11-07T11:08:27.200123 #1171] FATAL -- : [3a4f5e93-f355-4db9-829c-08cd9980a53e]
F, [2017-11-07T11:08:27.200185 #1171] FATAL -- : [3a4f5e93-f355-4db9-829c-08cd9980a53e] config/initializers/hydra_remote_identifier_config.rb:7:in `block (4 levels) in <top (required)>'
[3a4f5e93-f355-4db9-829c-08cd9980a53e] app/models/concerns/remotely_identified_by_doi.rb:81:in `identifier_request'
[3a4f5e93-f355-4db9-829c-08cd9980a53e] app/models/concerns/remotely_identified_by_doi.rb:55:in `apply_doi_assignment_strategy'
[3a4f5e93-f355-4db9-829c-08cd9980a53e] app/actors/hyrax/actors/image_actor.rb:11:in `save'
[3a4f5e93-f355-4db9-829c-08cd9980a53e] app/controllers/concerns/scholar/works_controller_behavior.rb:26:in `update'
```

It's unclear if other works are affected as well.  I've tested another work with a DOI and did not get this error.

NOTE: the save is happening while logged in as an admin user.  It's possible the error only happens for admins and not the work owner.

**Comment by jamesvanmil** [comment]
The method defined in `lib/scholar.rb`, `Scholar. permanent_url_for` is missing.

Compare the autoload paths:

My local development environment: 

```ruby
["/Users/vanmiljf/development/scholar_uc/app/presenters/concerns", #<Pathname:/Users/vanmiljf/development/scholar_uc/lib>, #<Pathname:/Users/vanmiljf/development/scholar_uc/services>, #<Pathname:/Users/vanmiljf/development/scholar_uc/jobs>, "app/models/datastreams", "/Users/vanmiljf/.rvm/gems/ruby-2.4.1@scholar/bundler/gems/orcid-728d7dcdf1ac/app/services", "/Users/vanmiljf/.rvm/gems/ruby-2.4.1@scholar/bundler/gems/devise-multi_auth-24bc234191a2/app/services"]
```

The production environment: 

```ruby
["/srv/apps/curate_uc/app/presenters/concerns", #<Pathname:/srv/apps/curate_uc/lib>, #<Pathname:/srv/apps/curate_uc/services>, #<Pathname:/srv/apps/curate_uc/jobs>, "app/models/datastreams", "/srv/apps/curate_uc/vendor/bundle/ruby/2.4.0/bundler/gems/orcid-728d7dcdf1ac/app/services", "/srv/apps/curate_uc/vendor/bundle/ruby/2.4.0/bundler/gems/devise-multi_auth-24bc234191a2/app/services"]
```
