### ISSUE TITLE
Space char in new work required field results in error

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#588]
Inputting space characters only, in a required field, in a new work results in error in test mode and on qa.

```
Blacklight::Exceptions::InvalidSolrID in CurationConcern::ArticlesController#create
The solr permissions search handler didn't return anything for id "sufia:ww72bb58w"
```
```
Completed 500 Internal Server Error in 216ms

Blacklight::Exceptions::InvalidSolrID (The solr permissions search handler didn't return anything for id "sufia:ww72bb58w"):
  hydra-access-controls (6.4.2) lib/hydra/permissions_query.rb:33:in `get_permissions_solr_response_for_doc_id'
  hydra-access-controls (6.4.2) lib/hydra/permissions_query.rb:11:in `permissions_doc'
  hydra-access-controls (6.4.2) lib/hydra/ability.rb:113:in `edit_groups'
  /Users/crowesn/Development/curate/app/models/concerns/curate/ability.rb:109:in `test_edit_fedora_object'
  /Users/crowesn/Development/curate/app/models/concerns/curate/ability.rb:71:in `test_edit'
  /Users/crowesn/Development/curate/app/models/concerns/curate/ability.rb:35:in `block in edit_permissions'
  cancan (1.6.10) lib/cancan/rule.rb:34:in `call'
  cancan (1.6.10) lib/cancan/rule.rb:34:in `matches_conditions?'
  cancan (1.6.10) lib/cancan/ability.rb:58:in `block in can?'
  cancan (1.6.10) lib/cancan/ability.rb:57:in `each'
  cancan (1.6.10) lib/cancan/ability.rb:57:in `detect'
  cancan (1.6.10) lib/cancan/ability.rb:57:in `can?'
  cancan (1.6.10) lib/cancan/controller_additions.rb:380:in `can?'
  actionpack (4.0.13) lib/abstract_controller/helpers.rb:53:in `can?'
  /Users/crowesn/Development/curate/app/views/curation_concern/base/_related_files.html.erb:60:in `___sers_crowesn__evelopment_curate_app_views_curation_concern_base__related_files_html_erb__334105257436225310_70249420986160'
  actionpack (4.0.13) lib/action_view/template.rb:143:in `block in render'
  activesupport (4.0.13) lib/active_support/notifications.rb:161:in `instrument'
  actionpack (4.0.13) lib/action_view/template.rb:141:in `render'
  actionpack (4.0.13) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
  actionpack (4.0.13) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
  actionpack (4.0.13) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.13) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (4.0.13) lib/action_view/renderer/partial_renderer.rb:278:in `render'
  actionpack (4.0.13) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionpack (4.0.13) lib/action_view/helpers/rendering_helper.rb:27:in `render'
  /Users/crowesn/Development/curate/app/views/curation_concern/base/show.html.erb:11:in `___sers_crowesn__evelopment_curate_app_views_curation_concern_base_show_html_erb__1239478186455164639_70249419475460'
  actionpack (4.0.13) lib/action_view/template.rb:143:in `block in render'
  activesupport (4.0.13) lib/active_support/notifications.rb:161:in `instrument'
  actionpack (4.0.13) lib/action_view/template.rb:141:in `render'
  actionpack (4.0.13) lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
  actionpack (4.0.13) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.13) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (4.0.13) lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
  actionpack (4.0.13) lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
  actionpack (4.0.13) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
  actionpack (4.0.13) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionpack (4.0.13) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionpack (4.0.13) lib/action_view/renderer/renderer.rb:23:in `render'
  actionpack (4.0.13) lib/abstract_controller/rendering.rb:127:in `_render_template'
  actionpack (4.0.13) lib/action_controller/metal/streaming.rb:219:in `_render_template'
  actionpack (4.0.13) lib/abstract_controller/rendering.rb:120:in `render_to_body'
  actionpack (4.0.13) lib/action_controller/metal/rendering.rb:33:in `render_to_body'
  actionpack (4.0.13) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
  actionpack (4.0.13) lib/abstract_controller/rendering.rb:97:in `render'
  actionpack (4.0.13) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.0.13) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/crowesn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
  activesupport (4.0.13) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.0.13) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:40:in `render'
  /Users/crowesn/Development/curate/app/controllers/curation_concern/generic_works_controller.rb:43:in `block (2 levels) in create'
  actionpack (4.0.13) lib/action_controller/metal/responder.rb:231:in `call'
  actionpack (4.0.13) lib/action_controller/metal/responder.rb:231:in `default_render'
  actionpack (4.0.13) lib/action_controller/metal/responder.rb:161:in `to_html'
  actionpack (4.0.13) lib/action_controller/metal/responder.rb:154:in `respond'
  actionpack (4.0.13) lib/action_controller/metal/responder.rb:147:in `call'
  actionpack (4.0.13) lib/action_controller/metal/mime_responds.rb:330:in `respond_with'
  /Users/crowesn/Development/curate/app/controllers/curation_concern/generic_works_controller.rb:42:in `create'
  actionpack (4.0.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.0.13) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.13) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.13) lib/active_support/callbacks.rb:533:in `_run__4475360300791765737__process_action__callbacks'
  activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.0.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.13) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.13) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.13) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.13) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.13) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.0.13) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:676:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.13) lib/active_record/migration.rb:373:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.13) lib/active_support/callbacks.rb:373:in `_run__519007474974340864__call__callbacks'
  activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
  /Users/crowesn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /Users/crowesn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /Users/crowesn/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by lawhorkl** [comment]
Pending a pull request to close this.
